### ISSUE TITLE
[1.7.10] Request support for Botania's Resolute Ivy

### ISSUE THREAD

**Issue by thephoenixlodge** [cyanobacterium/DrCyanos_Lootable-Bodies#11]
The Botania Resolute Ivy acts to allow the player to keep the item it is applied to after death, but currently this does not work as intended and the item will get grabbed by the lootable body instead of respawning with the player. Any chance this could have support added in the 1.7.10 version, even if it involved a pull request by someone else?
I'll also put this issue on the Botania github.

**Comment by cyanobacterium** [comment]
I'd be willing to add such a feature to the 1.8 version, but I have no plans for further development with Minecraft 1.7.10.

**Comment by cyanobacterium** [comment]
The rewrite of Lootable Bodies for Minecraft 1.9 (Lootable Bodies version 2.0.0) properly checks for witheld items on death.
