### ISSUE TITLE
All items appear X2 in corpse with CyanosLootableBodies-1.7.10-backport_1.3.6

### ISSUE THREAD

**Issue by ProsperCraft** [cyanobacterium/DrCyanos_Lootable-Bodies#12]
All of my items when I get back to my corpse appear to have duplicated, but  the duplicated items dissapear when you click with them.

modlist- http://pastebin.com/NeZFZifZ

**Comment by cyanobacterium** [comment]
Does this happen if you play with just the Lootable Bodies mod and no other mods installed? If not, then put your other mods back in until the problem re-appears and let me know which combination of mods results in this behavior.

**Comment by ProsperCraft** [comment]
This resolved removing the AVP mod.
