### ISSUE TITLE
Odd Interaction with Tinkers' Construct Smeltery

### ISSUE THREAD

**Issue by thor12022** [cyanobacterium/DrCyanos_Lootable-Bodies#15]
It seems that having an invulnerable body in a Tinker's Construct Smeltery will result in the Smeltery filling up with blood as it thinks it's damaging the body. 

Great for infinite Congealed Blood, bad for using the Smeltery.

This happens with:
Lootable Bodies 1.7.10-backport_1.3.6
Tinker's Construct 1.7.10-1.8.8

[Config File](https://github.com/FeedTheCreeper/TheFeedTheCreeperPack/blob/4.0.0/config/lootablebodies.cfg)

**Comment by cyanobacterium** [comment]
The lootable body uses the living entity class. I can't really do much about it, so I recommend making the corpses vulnerable to "other" damage and giving them 20 health. That will let you sacrifice bodies for blood in a way that isn't too OP.
