### ISSUE TITLE
Lootable Body counts as valid target for Wither

### ISSUE THREAD

**Issue by thor12022** [cyanobacterium/DrCyanos_Lootable-Bodies#17]
Withers count the Lootable body as a valid target, this gets particularly interesting when they are set to be invulnerable.

Unless this is intended/acceptable, making the Body Undead causes the Wither to not target it.

*`e.g.*
```java
@Override
public EnumCreatureAttribute getCreatureAttribute()
{
   return EnumCreatureAttribute.UNDEAD;
}
```

Not sure about any other side effects of this.

**Comment by cyanobacterium** [comment]
That's a good idea. I'll do that and push an update.
