### ISSUE TITLE
[Issue] Targeting a body

### ISSUE THREAD

**Issue by Elsys656** [cyanobacterium/DrCyanos_Lootable-Bodies#18]
It's really difficult for me to target my body to open it as an inventory quite often I hover over the body with my targeting cursor and it doesn't recognize it's there.

MC 1.7.10
Cyno's Lootable Bodies 1.3.5-backport.jar

Will try the latest version whats the recommended version of forge for this mod as well?

**Comment by cyanobacterium** [comment]
Try looking at the body's waist when you try to interact with it. 

I compiled the backport with Forge-1.7.10-10.13.2.1230
