### ISSUE TITLE
Falling into the void is never fun

### ISSUE THREAD

**Issue by TBone311xXx** [cyanobacterium/DrCyanos_Lootable-Bodies#25]
When one might mistakenly miss-step into the void, via random teleportation or an ever so persistent abyssal zombie on the spawn platform in the end, ones stuff is permanently irretrievable. An undesirable way for all of ones stuff to go to waste indeed. Perhaps a remedy is in order, as this could be quite irritating when one has no control over such an outcome. Spawning the lootable body on ones bed would suffice, perhaps even a valuable craft-able relic that would be consumed on such an occasion would also suffice.

**Comment by Divineaspect** [comment]
This is proving to be a surprisingly frequent occurance.

**Comment by HoldYourWaffle** [comment]
Or let the corpse spawn on the last (stable-)block the player was standing on

**Comment by MentalMouse** [comment]
For the End in particular, you could put it on the spawn platform or near the return gate.  That doesn't seem to help with the more general case (void ages, void utility dimensions, Deep Dark, etc), but AIUI all dimensions do in fact have a spawn point, even if they're unbeddable.  It might be necessary to generate a platform there if there are no solid blocks present.

**Comment by jriwanek** [comment]
Code welcome. It'll be a while otherwise till I can work on it.

**Comment by jriwanek** [comment]
Fixed in latest dev for 1.12.2
