### ISSUE TITLE
Baubles

### ISSUE THREAD

**Issue by Samuell1** [cyanobacterium/DrCyanos_Lootable-Bodies#4]
If i dead with items in baubles menu. Items destroyed.

version: 1.3.0-backport

**Comment by cyanobacterium** [comment]
I am unable to replicate your problem.

I installed the Baubles mod and Lootable Bodies 1.3.0-backport, put the Miner's Ring item in a baubles slot, and then jumped into a pool of lava (dimensions 2x2x2  blocks). All of my items, including the Miner's Ring, were in the corpse.

I will need detailed, step-by-step instructions on how to replicate the problem for me to debug. I will also need to know whether the bauble item normally falls to the floor when you die without having the Lootable Bodies mod installed.
