### ISSUE TITLE
[Crash] CyanosLootableBodies-1.2.0-backport (Forge 10.13.2.1236 + Forge 10.13.2.1264)

### ISSUE THREAD

**Issue by Carbon-Key** [cyanobacterium/DrCyanos_Lootable-Bodies#5]
Hello!  I hate this to be our first interaction since I had intended that to be a thankful forum post for your mod, however I have run into a little problem that is preventing me from committing this mod to my pack.  I already made a post about this over at Thermal Expansion so I hope you don't mind if I quote myself from there as well as some of that developer's remarks.

Previous Post:
Hopefully I've just done something stupid here and we can all laugh at me and move along. http://pastebin.com/wm3z4bBf should give you a list of the mods I've put together and http://pastebin.com/z2ew0ree should be the crash log. The list of mods is from me typing what appeared on the list in the "Mods" menu in my client. If there is a better/more readable method of displaying what I have installed then I will try to supply you with that. On to the issue! I got a crash apparently trying to render an energy cell inside of a lootable body container (inventory) from Dr. Cyano's Lootable Bodies mod. The log screamed at me about Thermal Expansion so I thought to try here first but if you think the issue is with the lootable bodies mod then I will post there as well. When I put a cell inside of a standard inventory (e.g. a vanilla chest) and attempt to access it I get no crash, it seems to just be when accessing the lootable body created after killing myself. I was getting some funny render glitches outside of the body gui though when i had the Cell in my hand. The included screenshot shows an example of this.
![2015-01-10_15 51 40](https://cloud.githubusercontent.com/assets/10481639/5805266/634b897a-9fdb-11e4-8df2-8674f43ddc95.png)
The effect stopped as soon as I switched to another slot in my hotbar. That screenshot was taken using Forge 10.13.2.1236, after upgrading to 10.13.2.1264 I have been able to reproduce the crash consistently, but not the weird rendering bug from the screenshot. Hope you can make more sense of this than I can! I look forward to hearing from you soon, thanks. :D

...

The cell is the only thing I have seen this happen with, as you can see in the screenshot i tried it with a few other blocks in hand and nothing bad happened. I did discover however that the weird effects from the screenshot in my first post are reproducible by dying with the item in hand. These tests were done in a new world just to make sure it wasn't about the save file.
![2015-01-10_23 10 21](https://cloud.githubusercontent.com/assets/10481639/5805298/94fd8b8a-9fdb-11e4-98a7-051caa399c02.png)

:End Previous Post

Skyboy's Response:
The render issue is caused by lootable bodies not properly pushing all the necessary GL states before letting items render.

The metadata issue appears to be that lootable bodies is re-creating the item incorrectly and using the display damage value instead of the actual damage value (which is easily avoided by using the item it has (there's even a .copy() method if it needs copied) instead of attempting to re-create it in a wholly incorrect manner).

:End Skyboy's Response

I hope all this text isn't a bother, I just wanted you to have most of the info in one place to start with.  Here is a link to the original issue if you would like to read the whole thing https://github.com/CoFH/Feedback/issues/11.  I hope to hear back from you soon as I love your mod and would hate to not include it in my pack because of this issue.  Thank you so much for your time!

**Comment by cyanobacterium** [comment]
I'm looking into it now. Minecraft 1.8 does rendering differently and 
has defferent methods for comparing items than Minecraft 1.7.10, which 
has caused most of the bugs so far in the backport, so I suspect this is 
another such bug.

-DrCyano

**Comment by cyanobacterium** [comment]
It looks like, based on the issue thread, that the problem is that the 
energy cell reports itself to be damageable, but uses the damage value 
for metadata. The solution, for now, is to upgrade to Lootable Bodies 
version 1.3.0 and set *item_damage_on_death=0* in the config file.

-DrCyano

**Comment by Carbon-Key** [comment]
Thanks for your help!  I changed the config and I'm having no issues now. :D
