### ISSUE TITLE
Severe Client Side Spam

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/DrCyanos_Lootable-Bodies#7]
Not sure if it is your mod or Royalsmod's Quartz & Prismarine mod doing it.

https://gist.github.com/kreezxil/f94b197fb5fb904972e3#file-gistfile1-txt

**Comment by cyanobacterium** [comment]
It appears that Royalsmod's Quartz & Prismarine mod assumes that only players wear the armor (the corpses in Lootable Bodies are not player entities). I bet you'd get the same problem if you use the /summon command to create a zombie wearing the armor (and that would confirm that this is a problem with Royalsmod's Quartz & Prismarine). 

The author of Royalsmod's Quartz & Prismarine could fix the spam by adding a class check (e.g. "if(e instanceof EntityPlayer)"), but some aspect of the armor rendering would remain non-functional while on the corpse.

**Comment by kreezxil** [comment]
Thanks I'll pass this on.

-----Original Message-----
