### ISSUE TITLE
[Backport] Include mcmod.info file

### ISSUE THREAD

**Issue by bochen415** [cyanobacterium/DrCyanos_Lootable-Bodies#9]
As title

I'm using [solder.io](http://solder.io) and [TechnicSolderHelper](https://github.com/zlepper/TechnicSolderHelper) for automating the modpack build process and all the mods without that file need manual input. It gets messy, names are garbled..

**Comment by skittishtrigger** [comment]
Bumping this for several reasons.

1: Popular mod that is well done
2: I too use solder for versioning control and as tmph gets more popular I see it being wanted in ftb/at/technic more too
3: Helps with consistent naming architecture

Love the mod though :)

**Comment by cyanobacterium** [comment]
I couldn't get my buildscript to include it properly, so I manually inserted the file into the 1.3.5-backport jar. Re-download the latest release and the file will be there.

**Comment by bochen415** [comment]
Thank you good sir.
@TehNut does it automagically in his repos, you can look at that but idk if you want a lot of work put in a backport.

**Comment by cyanobacterium** [comment]
Thanks for the advice, but my 1.7.10 project is a mess and I refuse to touch it ever again (all of my 1.7.10 projects are messy because I didn't yet understand how to properly use eclipse).
